= Описание тестового проекта

Данный проект представляет собой монолитное приложение, состоящее из фронтенда и бэкенда. 

Фронтенд реализован на фреймворке Angular. Бэкенд реализован на фреймворке Spring.

= Установка локально

0. Установить IntelliJ IDEA https://www.jetbrains.com/ru-ru/idea/ (Ultimate, пробная версия 30 дней)
1. Установить Java 11 https://adoptopenjdk.net/
2. Установить Node.js https://nodejs.org/en/ (LTS 64-битную версию)
3. Установить Git https://git-scm.com/
4. Установить Docker Desktop https://www.docker.com/get-started
5. Склонировать проект к себе (В IntelliJ IDEA File -> New.. -> Project from Version Control.. и вставить URL из репозитория)
6. Найти папку src/main/docker/postgresql.yml и запустить blog-postgresql (Докер должен быть запущен)
7. Зайти в корневую папку проекта и выполнить команду:
`./mvnw`
8. Приложение будет доступно по адресу http://localhost:8080

= Jira и Confluence для ведения тестовой документации

Jira https://qa-testproject.atlassian.net
Confluence https://qa-testproject.atlassian.net/wiki/home




